// Bucle de capturas de NARSIL Pass sobre la compilación de demostración (ui/dist-demo, puente en
// memoria). Recorre las pantallas como un operador y falla si hay errores de consola o de página.
//   node scripts/capturas.mjs [--ancho 1366 --alto 768] [--idioma es]
import { chromium } from '../ui/node_modules/playwright/index.mjs'
import { mkdirSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import path from 'node:path'

const raiz = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const arg = (n, d) => { const i = process.argv.indexOf(`--${n}`); return i > 0 ? process.argv[i + 1] : d }
const ancho = Number(arg('ancho', 1366)), alto = Number(arg('alto', 768))
const salida = path.join(raiz, 'capturas', `${ancho}x${alto}`)
mkdirSync(salida, { recursive: true })
const url = pathToFileURL(path.join(raiz, 'ui', 'dist-demo', 'index.html')).href

const navegador = await chromium.launch()
const pagina = await (await navegador.newContext({ viewport: { width: ancho, height: alto } })).newPage()
const errores = []
pagina.on('console', (m) => { if (m.type() === 'error') errores.push(m.text()) })
pagina.on('pageerror', (e) => errores.push(e.message))
const foto = async (n) => { await pagina.waitForTimeout(350); await pagina.screenshot({ path: path.join(salida, `${n}.png`) }); console.log('✓', n) }

await pagina.goto(url)
await pagina.getByRole('button', { name: 'Desbloquear' }).waitFor()
await foto('01-desbloqueo')
await pagina.locator('input[type=password]').fill('mala')
await pagina.keyboard.press('Enter')
await pagina.getByRole('alert').waitFor()
await foto('02-clave-erronea')
await pagina.locator('input[type=password]').fill('demo')
await pagina.keyboard.press('Enter')
await pagina.getByText('Intranet de la unidad').first().waitFor()
await foto('03-toda-la-base')
await pagina.locator('.lista').evaluate((n) => n.scrollTo(0, 99999))
await foto('03b-toda-la-base-final')
await pagina.locator('.vista').filter({ hasText: 'Servicios internos' }).click()
await pagina.getByText('Intranet de la unidad').first().click()
await foto('04-entrada-repetida')
await pagina.getByText('Infraestructura').first().click()
await pagina.getByText('VPN corporativa').first().click()
await foto('05-entrada-adjunto')
await pagina.getByText('VPN corporativa').first().click({ button: 'right' })
await foto('06-menu-contextual')
await pagina.keyboard.press('Escape')
await pagina.getByRole('button', { name: 'Editar' }).first().click()
await foto('07-editor')
await pagina.locator('.editor input').first().fill('VPN corporativa (cambio)')
await pagina.keyboard.press('Escape')
await pagina.getByText('Descartar cambios').waitFor()
await foto('08-descartar-cambios')
await pagina.getByRole('button', { name: 'Descartar' }).click()
await pagina.locator('.vista').filter({ hasText: 'Servicios externos' }).click()
await pagina.getByText('Correo de la operación').first().click()
await foto('09-externos-totp')
await pagina.getByRole('button', { name: 'Filtros' }).click()
await pagina.locator('.filtros select').nth(2).selectOption('cualquiera')
await foto('10-filtro-avisos')
await pagina.getByText('Quitar filtros').click()
await pagina.getByRole('button', { name: 'Filtros' }).click()
await pagina.locator('.vista').filter({ hasText: 'Identidades operativas' }).click()
await pagina.getByText('Marta Ribas').first().click()
await pagina.waitForTimeout(300)
await foto('11-identidad-ficha')
await pagina.locator('.pestanas--detalle .pestana').nth(1).click()
await foto('12-identidad-servicios')
await pagina.locator('.pestanas--detalle .pestana').nth(2).click()
await foto('13-identidad-fotos')
await pagina.locator('.miniatura').first().click()
await foto('14-visor')
await pagina.keyboard.press('ArrowRight')
await foto('15-visor-siguiente')
await pagina.keyboard.press('Escape')
await pagina.locator('.pestanas--detalle .pestana').nth(3).click()
await foto('16-identidad-biografia')
await pagina.getByRole('button', { name: 'Editar' }).first().click()
await foto('17-editor-identidad-ficha')
await pagina.locator('.editor').evaluate((n) => n.closest('.columna')?.scrollTo(0, 99999))
await foto('18-editor-identidad-ficha-final')
await pagina.locator('.editor .pestanas--detalle .pestana').nth(1).click()
await pagina.locator('.editor').evaluate((n) => n.closest('.columna')?.scrollTo(0, 0))
await foto('19-editor-identidad-servicios')
await pagina.locator('.editor .pestanas--detalle .pestana').nth(3).click()
await foto('20-editor-identidad-cuenta')
await pagina.getByRole('button', { name: 'Cancelar' }).click()
await pagina.getByRole('button', { name: 'Nueva identidad operativa' }).first().click()
await pagina.locator('.menu').getByText('Nueva identidad operativa').click()
await foto('21-nueva-identidad')
await pagina.getByRole('button', { name: 'Cancelar' }).click()
await pagina.getByRole('button', { name: 'Salud' }).click()
await foto('22-salud-repetidas')
await pagina.locator('.dialogo .pestana').nth(2).click()
await foto('23-salud-renovar')
await pagina.locator('.dialogo .pestana').nth(3).click()
await foto('24-salud-caducidad')
await pagina.locator('.dialogo .salud__fila').first().click()
await foto('25-ir-desde-salud')
await pagina.keyboard.press('F1')
await foto('26-atajos')
await pagina.keyboard.press('Escape')
await pagina.locator('.buscador input').fill('unidad')
await pagina.waitForTimeout(300)
await foto('27-busqueda-global')
await pagina.locator('.buscador input').fill('lisboa')
await foto('27b-busqueda-identidad')
await pagina.locator('.buscador input').fill('')
await pagina.locator('.vista').filter({ hasText: 'Toda la base' }).click()
await foto('28-toda-la-base')
await pagina.getByRole('button', { name: 'Ajustes' }).click()
await pagina.getByText('Base de datos', { exact: true }).last().click()
await foto('29-ajustes-base')
await pagina.keyboard.press('Escape')
await pagina.getByRole('button', { name: 'Generador' }).click()
await foto('30-generador')
await pagina.keyboard.press('Escape')
await pagina.getByRole('button', { name: 'Bloquear' }).click()
await pagina.getByRole('button', { name: 'Desbloquear' }).waitFor()
await pagina.getByRole('button', { name: 'Abrir base…' }).click()
await foto('31-bloqueada-otra-base')
await pagina.locator('select').last().selectOption('en')
await foto('32-desbloqueo-en')
await pagina.locator('input[type=password]').fill('demo')
await pagina.keyboard.press('Enter')
await pagina.getByText('Internal services').first().waitFor()
await pagina.locator('.vista').nth(3).click()
await pagina.getByText('Marta Ribas').first().click()
await foto('33-identidad-en')
await navegador.close()
const reales = errores.filter((e) => !/favicon/i.test(e))
if (reales.length) { console.log('ERRORES', reales); process.exit(1) }
console.log(`Capturas en ${salida}, sin errores de consola`)
